colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "linkedin-wallpaper.webp"
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
fathomAnalytics = {}
umamiAnalytics = {}
selineAnalytics = {}
buymeacoffee = {}
verification = {}
rssnext = {}
advertisement = {}
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = false
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
disableHeroImageFilter = false

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = false
showEdit = false
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 3
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = false
showWordCount = true
showComments = true
showZenMode = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyCJUh8_eWSkkvDZwHdrPNBdyke7Dk422uI"
authDomain = "phuchoang-sbs.firebaseapp.com"
projectId = "phuchoang-sbs"
storageBucket = "phuchoang-sbs.firebasestorage.app"
messagingSenderId = "359041758586"
appId = "1:359041758586:web:12cabd41bb64a6bda452c3"
measurementId = "G-HVDVFDQDMC"
