baseURL = "https://phuchoang.sbs"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Everyone, meet fel1x"

languageCode = "en"
languageName = "English"

copyright = "2025 Felix"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Pagination config
[pagination]
disableAliases = false
pagerSize = 3
path = "posts"

# Menu config
[menu]
[[menu.main]]
weight = 1
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Posts"
url = "/posts/"
[[menu.main]]
weight = 2
identifier = "projects"
pre = ""
post = ""
name = "Projects"
url = "projects"
[[menu.main]]
weight = 3
pre = ""
post = ""
name = "About me"
url = "about"
[[menu.main]]
weight = 4
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"

[params]
# site default theme ["auto", "light", "dark"]
defaultTheme = "auto"
dateFormat = "2006-01-02"
gitRepo = "https://github.com/phuchoang2603"
title = "Everyone, meet fel1x!"
description = "A blog about my life, my projects and my thoughts"

[params.author]
name = "Felix Hoang"
email = "xuanphuc.a1gv@gmail.com"

[params.header]
desktopMode = "auto"
mobileMode = "auto"
# Header title config
[params.header.title]
logo = ""
name = "Everyone, meet fel1x!"
# you can add extra information before the name (HTML format is supported), such as icons
pre = "<i class='fa-solid fa-laptop' aria-hidden='true'></i>"
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
# whether to use typeit animation for title name
typeit = false # Header config

# Footer config
[params.footer]
enable = true
custom = ''
hugo = false
copyright = true
author = true
since = 2022

[params.search]
enable = true
# type of search engine ["lunr", "algolia"]
type = "lunr"
# max index length of the chunked content
contentLength = 4000
# placeholder of the search bar
placeholder = ""
# LoveIt NEW | 0.2.1 max number of results length
maxResultLength = 10
# LoveIt NEW | 0.2.3 snippet length of the result
snippetLength = 30
# LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
highlightTag = "em"
# LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
absoluteURL = false

# Home page config
[params.home]
# LoveIt NEW | 0.2.0 amount of RSS pages
rss = 10
# Home page profile
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = "xuanphuc.a1gv@gmail.com"
# URL of avatar shown in home page
avatarURL = "/images/avatar.png"
# LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
title = "Hello, my name is Felix!"
# subtitle shown in home page (HTML format is supported)
subtitle = "cs student @ USF"
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
disclaimer = ""
# Home page posts
[params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 3
defaultHiddenFromHomePage = false

[params.social]
GitHub = "phuchoang2603"
Linkedin = "phuchoang2603/"
Facebook = "phuchoang2603/"

[params.page]
# LoveIt NEW | 0.2.0 whether to hide a page from home page
hiddenFromHomePage = false
# LoveIt NEW | 0.2.0 whether to hide a page from search results
hiddenFromSearch = false
# LoveIt NEW | 0.2.0 whether to enable twemoji
twemoji = false
# whether to enable lightgallery
lightgallery = false
# LoveIt NEW | 0.2.0 whether to enable the ruby extended syntax
ruby = true
# LoveIt NEW | 0.2.0 whether to enable the fraction extended syntax
fraction = true
# LoveIt NEW | 0.2.0 whether to enable the fontawesome extended syntax
fontawesome = true
# whether to show link to Raw Markdown content of the content
linkToMarkdown = false
# LoveIt NEW | 0.2.4 whether to show the full text content in RSS
rssFullText = false
# LoveIt NEW | 0.2.0 Table of the contents config
[params.page.toc]
# whether to enable the table of the contents
enable = true
# LoveIt NEW | 0.2.9 whether to keep the static table of the contents in front of the post
keepStatic = false
# whether to make the table of the contents in the sidebar automatically collapsed
auto = true
# LoveIt CHANGED | 0.2.0 KaTeX mathematical formulas
[params.page.math]
enable = true
# LoveIt CHANGED | 0.2.11 default inline delimiter is $ ... $ and \( ... \)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# LoveIt CHANGED | 0.2.11 default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
blockLeftDelimiter = ""
blockRightDelimiter = ""
# KaTeX extension copy_tex
copyTex = true
# KaTeX extension mhchem
mhchem = true
# LoveIt NEW | 0.2.0 Code config
[params.page.code]
# whether to show the copy button of the code block
copy = true
# the maximum number of lines of displayed code by default
maxShownLines = 50

[params.page.share]
enable = false

[params.page.comment]
enable = true
# giscus comment config (https://giscus.app/)
[params.page.comment.giscus]
# You can refer to the official documentation of giscus to use the following configuration.
enable = true
repo = "phuchoang2603/phuchoang-sbs"
repoId = "R_kgDOOUB0Ww"
category = "General"
categoryId = "DIC_kwDOOUB0W84Coz7q"
# automatically adapt the current theme i18n configuration when empty
lang = ""
mapping = "pathname"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
lazyLoading = true
lightTheme = "light"
darkTheme = "dark"

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
lineNumbersInTable = false
# false is a necessary configuration
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

